spring.application.name=service-security

server.port=9100

# spring.datasource.url=jdbc:oracle:thin:@localhost:1521/FREEPDB1
# spring.datasource.username=superstore
# spring.datasource.password=superstore
# spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.datasource.url=jdbc:postgresql://localhost:5432/superstore
spring.datasource.username=superstore
spring.datasource.password=superstore
spring.datasource.driver-class-name=org.postgresql.Driver

# spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.fetch_size=100
# Open Session In View (OSIV) can cause N+1 query problems.
spring.jpa.open-in-view=false

jwt.private-key-location=file:c:/project/superstore/keys/private.pem
jwt.expiration-ms=86400000

# tells this service where the Eureka registry lives.
eureka.client.service-url.defaultZone=http://eureka:eureka@localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# keep registration enabled so it connects when Eureka comes online.
# eureka.client.enabled=false
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
# spring.liquibase.default-schema=public
spring.liquibase.default-schema=superstore
# spring.liquibase.liquibase-schema=public
spring.liquibase.liquibase-schema=superstore

# management.server.port=8079
# include prometheus in exposed endpoints
management.endpoints.web.exposure.include=health,prometheus
# optional : enable common metric tags (like application name)
management.metrics.tags.application=superstore
management.metrics.tags.service=${spring.application.name}
