spring.application.name=service-app

# the --debug flag instructs Spring Boot to print the Conditions Evaluation Report, showing which auto-configurations matched or failed to match.
# debug=true
# [OR] java -jar target/your-app-0.0.1-SNAPSHOT.jar --debug
# [OR] mvn spring-boot:run -Dspring-boot.run.arguments="--debug"
# [OR] expose beans and conditions endpoints over Web (HTTP) management.endpoints.web.exposure.include=beans,conditions

server.port=8080
backend.gateway-url=http://localhost:9000

spring.datasource.url=jdbc:oracle:thin:@localhost:1521/FREEPDB1
spring.datasource.username=superstore
spring.datasource.password=superstore
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.fetch_size=100
# Open Session In View (OSIV) can cause N+1 query problems.
spring.jpa.open-in-view=false

vaadin.launch-browser=true

spring.security.user.name=admin
spring.security.user.password=admin
spring.security.user.roles=ADMIN

# JMX is a built-in dashboard API for the Java Virtual Machine (JVM).
spring.jmx.enabled=true

# move Actuator outside of standard path scope
# management.endpoints.web.base-path=/api-actuator3
# management.server.port=8079
# include prometheus in exposed endpoints
# management.endpoints.web.exposure.include=*
management.endpoints.web.exposure.include=health,prometheus,beans,conditions,info,metrics,loggers,threaddump
management.endpoint.health.show-details=always
# optional : enable common metric tags (like application name)
management.metrics.tags.application=superstore

spring.data.redis.host=localhost
spring.data.redis.port=6379
# turn off automatic Spring Data Redis repositories which can try to connect to a server at startup.
spring.data.redis.repositories.enabled=false
# spring.session.data.redis.namespace=vaadin:session

# IMPORTANT
# only use secure cookies if you're actually on HTTPS locally.
# on HTTP localhost this causes the browser to silently drop the cookie -> new session -> loop.
# for local dev.
server.servlet.session.cookie.secure=false
# re-enable only in prod behind HTTPS.
# server.servlet.session.cookie.secure=true

# match the exact cookie name Vaadin searches for to avoid matching collisions.
server.servlet.session.cookie.name=JSESSIONID
server.servlet.session.cookie.path=/

# keeps Redis active for normal caching, but lets Vaadin manage UI sessions in RAM safely.
# spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.session.SessionAutoConfiguration

# incoming Request -> [ Session Filter (MIN_VALUE) ] -> [ Security Filter (-100) ] -> [ Controller ]
# -2147483648 represents Integer.MIN_VALUE
# spring.session.servlet.filter-order=-2147483648

# force Spring Session to write synchronously so Vaadin doesn't think the session is dead.
# 'immediate' writes on every minor state change, which breaks Vaadin's dynamic UI renders.
# 'on-save' save sessions to Redis only at the absolute end of a request response.
# spring.session.data.redis.flush-mode=immediate
# spring.session.data.redis.flush-mode=on-save
# force Spring Session to use normal HTTP Servlet cookies.
# spring.session.data.redis.repository-type = indexed
# spring.session.data.redis.repository-type = default
# stops Redis from trying to serialize Vaadin's background ASYNC/WebSocket channels.
# spring.session.servlet.filter-dispatcher-types=request,forward,async
# force Spring Session to use native Java serialization.
# spring.session.redis.serializer-type=jdk

# logging.level.org.springframework.security=DEBUG
# logging.level.org.springframework.session=DEBUG
# logging.level.org.springframework.web=DEBUG
# logging.level.com.vaadin=DEBUG
# logging.level.com.vaadin.flow.router=TRACE

# set session timeout
#server.servlet.session.timeout=30m

# a secure base64 encoded HMAC-SHA256 key (keep this secret)
# jwt.secret=6x+B8K2N9qZ3wXvY5rT7mP1sQ9uV4xZ8A2bC5dE6fG7hI8jK9lM0nO1pQ2rS3tU4
# spring.security.oauth2.resourceserver.jwt.public-key-location=file:c:/project/superstore/keys/public.pem

# turn down the logging level for this specific Vaadin internal handler
# logging.level.com.vaadin.flow.server.communication.ReturnChannelHandler=ERROR

