spring.application.name=service-product

server.port=8081

# spring.datasource.url=jdbc:oracle:thin:@localhost:1521/FREEPDB1
# spring.datasource.username=superstore
# spring.datasource.password=superstore
# spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.datasource.url=jdbc:postgresql://localhost:5432/superstore
spring.datasource.username=superstore
spring.datasource.password=superstore
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.fetch_size=100

# Open Session in View (OSIV) can cause N+1 query problems.
spring.jpa.open-in-view=false

spring.security.user.name=admin
spring.security.user.password=admin
spring.security.user.roles=ADMIN

#management.server.port=8079
# include prometheus in exposed endpoints
management.endpoints.web.exposure.include=health,prometheus
# optional : enable common metric tags (like application name)
management.metrics.tags.application=superstore

#APACHE KAFKA
spring.kafka.bootstrap-servers=localhost:9092
# AdminClient (startup)
# checks if Kafka is alive and to verify topics and auto create if needed.
# (default is usually 120000 / 2 mins)
# wait time for each request.
spring.kafka.admin.properties.request.timeout.ms=3000
# total wait time.
spring.kafka.admin.properties.default.api.timeout.ms=3000
# AdminClient (runtime)
spring.kafka.properties.request.timeout.ms=3000
spring.kafka.properties.default.api.timeout.ms=3000
# retry connection (default is 50ms, which is why it spams).
spring.kafka.properties.reconnect.backoff.ms=1000
spring.kafka.properties.reconnect.backoff.max.ms=3000
# tell the Producer not to block forever if Kafka is down.
spring.kafka.producer.properties.max.block.ms=3000
# tell the Consumer not to block forever if Kafka is down.
spring.kafka.listener.auto-startup=false
spring.kafka.consumer.properties.max.block.ms=3000
spring.kafka.consumer.properties.retry.backoff.ms=1000
spring.kafka.consumer.properties.reconnect.backoff.max.ms=3000
# disable automatic TOPIC creation.
#spring.kafka.admin.auto-create=false
# kafka isn't up, don't crash, just log the issue and boot the application.
spring.kafka.admin.fail-fast=false
# completely silences the internal connection/rebootstrap log spam.
logging.level.org.apache.kafka.clients.admin.internals.AdminMetadataManager=WARN
logging.level.org.apache.kafka.clients.NetworkClient=WARN

#spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
#spring.jackson.time-zone=GMT+5:30

spring.cache.type=redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# a secure base64 encoded HMAC-SHA256 key (keep this secret)
# jwt.secret=6x+B8K2N9qZ3wXvY5rT7mP1sQ9uV4xZ8A2bC5dE6fG7hI8jK9lM0nO1pQ2rS3tU4
# spring.security.oauth2.resourceserver.jwt.public-key-location=file:c:/project/superstore/keys/public.pem
jwt.public-key-location=file:c:/project/superstore/keys/public.pem

# tells this service where the Eureka registry lives.
eureka.client.service-url.defaultZone=http://eureka:eureka@localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# keep registration enabled so it connects when Eureka comes online.
# eureka.client.enabled=false
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true

# tells the client to wait longer between initial connection attempts (Default is 30).
eureka.client.initial-instance-info-replication-interval-seconds=60

# tells the client how often to retry fetching the registry if it fails (Default is 30).
eureka.client.registry-fetch-interval-seconds=60

# SILENCE THE LOG SPAM : hide the massive stack traces while it waits for Eureka.
logging.level.com.netflix.discovery=ERROR
logging.level.org.springframework.cloud.netflix.eureka=ERROR

# Spring AI Ollama
# What does temperature = 0.3 do?
# .temperature controls the randomness and creativity of the AI model's responses.
# low values  (0.0 – 0.3)  : make the output focused, deterministic, and factual.
# high values (0.7 – 1.0+) : Make the output more creative, diverse, and unpredictable.
# by setting it to 0.3, we are configuring our local LLM to give consistent, conservative, and precise answers - ideal for factual Q&A.  
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.model=llama3.2:1b
spring.ai.ollama.chat.temperature=0.3

spring.ai.ollama.embedding.model=nomic-embed-text
# limit context size (default 4096 or 8192)
spring.ai.ollama.chat.num-ctx=2048
# limits models maximum response length
spring.ai.ollama.chat.num-predict=256
# keeps ollama loaded indefinitely
spring.ai.ollama.chat.keep-alive=-1s
# set physical CPU core count (not logical hyperthreads)
spring.ai.ollama.chat.num-thread=4

# Spring AI PGVector
spring.ai.vectorstore.pgvector.index-type=HNSW
spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE
spring.ai.vectorstore.pgvector.dimensions=768
spring.ai.vectorstore.pgvector.initialize-schema=false
spring.ai.vectorstore.pgvector.schema-name=superstore
spring.ai.vectorstore.pgvector.table-name=vector_store
spring.ai.vectorstore.pgvector.id-type=text

# Spring AI MCP server
spring.ai.mcp.server.name=service-product-mcp-server
spring.ai.mcp.server.version=1.0.0
# spring.ai.mcp.server.type=ASYNC
spring.ai.mcp.server.protocol=STREAMABLE
# OPTIONAL : disable STDIO if it's running simultaneously
spring.ai.mcp.server.stdio=false
# streamable HTTP endpoint (default is /mcp)
spring.ai.mcp.server.streamable-http.mcp-endpoint=/mcp
spring.ai.mcp.server.streamable-http.keep-alive-interval=30s