# vaadin.launch-browser=true

spring.application.name=service-eureka

server.port=8761

# tells Eureka it is the server and shouldn't try to register with a peer.
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

spring.security.user.name=eureka
spring.security.user.password=eureka