# vaadin.launch-browser=true

spring.application.name=service-eureka

server.port=8761

# tells Eureka it is the server and shouldn't try to register with a peer.
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

spring.security.user.name=eureka
spring.security.user.password=eureka

eureka.client.service-url.defaultZone=http://eureka:eureka@localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

eureka.server.peer-node-read-timeout-ms=5000
eureka.server.peer-node-connect-timeout-ms=5000

# management.server.port=8079
# include prometheus in exposed endpoints
management.endpoints.web.exposure.include=health,prometheus
# optional : enable common metric tags (like application name)
management.metrics.tags.application=superstore
management.metrics.tags.service=${spring.application.name}
