# vaadin.launch-browser=true

spring.application.name=service-gateway

server.port=9000
# connect gateway to Eureka.
eureka.client.service-url.defaultZone=http://eureka:eureka@localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# --- ROUTE 1 : service-security via Eureka ---
spring.cloud.gateway.server.webflux.routes[0].id=route-service-security
# lb:// tells Spring to look up 'service-security' registered in Eureka.
spring.cloud.gateway.server.webflux.routes[0].uri=lb://service-security
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/auth/**

# --- ROUTE 2 : service-product via Eureka ---
spring.cloud.gateway.server.webflux.routes[1].id=route-service-product
# lb:// tells Spring to look up 'service-product' registered in Eureka.
spring.cloud.gateway.server.webflux.routes[1].uri=lb://service-product
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/product/**

# --- ROUTE 3 : service-order via Eureka ---
spring.cloud.gateway.server.webflux.routes[2].id=route-service-order
# lb:// tells Spring to look up 'service-order' registered in Eureka.
spring.cloud.gateway.server.webflux.routes[2].uri=lb://service-order
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/order/**

# --- ROUTE 4 : service-chatbot via Eureka ---
spring.cloud.gateway.server.webflux.routes[3].id=route-service-chatbot
# lb:// tells Spring to look up 'service-chatbot' registered in Eureka.
spring.cloud.gateway.server.webflux.routes[3].uri=lb://service-chatbot
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/chatbot/**

spring.main.web-application-type=reactive

# keep registration enabled so it connects when Eureka comes online.
# eureka.client.enabled=false
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true

# tells the client to wait longer between initial connection attempts (Default is 30).
eureka.client.initial-instance-info-replication-interval-seconds=60

# tells the client how often to retry fetching the registry if it fails (Default is 30).
eureka.client.registry-fetch-interval-seconds=60

# SILENCE THE LOG SPAM : hide the massive stack traces while it waits for Eureka.
logging.level.com.netflix.discovery=ERROR
logging.level.org.springframework.cloud.netflix.eureka=ERROR

# a secure base64 encoded HMAC-SHA256 key (keep this secret)
# jwt.secret=6x+B8K2N9qZ3wXvY5rT7mP1sQ9uV4xZ8A2bC5dE6fG7hI8jK9lM0nO1pQ2rS3tU4
# spring.security.oauth2.resourceserver.jwt.secret-key=6x+B8K2N9qZ3wXvY5rT7mP1sQ9uV4xZ8A2bC5dE6fG7hI8jK9lM0nO1pQ2rS3tU4
jwt.public-key-location=file:c:/project/superstore/keys/public.pem