# vaadin.launch-browser=true

spring.application.name=service-gateway

server.port=9000
# connect gateway to Eureka.
eureka.client.service-url.defaultZone=http://eureka:eureka@localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

spring.data.redis.host=localhost
spring.data.redis.port=6379
# spring.data.redis.timeout=5000ms
# spring.data.redis.connect-timeout=5000ms
# optional: disable Redis health check from marking the whole app unhealthy
# management.health.redis.enabled=false
# turn off automatic Spring Data Redis repositories which can try to connect to a server at startup.
spring.data.redis.repositories.enabled=false

# --- ROUTE 1 : service-security via Eureka ---
spring.cloud.gateway.server.webflux.routes[0].id=route-service-security
# lb:// tells Spring to look up 'service-security' registered in Eureka.
spring.cloud.gateway.server.webflux.routes[0].uri=lb://service-security
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/auth/**

# --- ROUTE 2 : service-product via Eureka ---
spring.cloud.gateway.server.webflux.routes[1].id=route-service-product
# lb:// tells Spring to look up 'service-product' registered in Eureka.
spring.cloud.gateway.server.webflux.routes[1].uri=lb://service-product
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/product/**

# --- ROUTE 3 : service-order via Eureka ---
spring.cloud.gateway.server.webflux.routes[2].id=route-service-order
# lb:// tells Spring to look up 'service-order' registered in Eureka.
spring.cloud.gateway.server.webflux.routes[2].uri=lb://service-order
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/order/**
# CIRCUIT BREAKER CONFIGURATION: the Circuit Breaker prevents a cascading failure when calling the service by failing fast when errors threshold is breached.
# activates Spring Cloud Gateway's CircuitBreakerGatewayFilterFactory
spring.cloud.gateway.server.webflux.routes[2].filters[0].name=CircuitBreaker
# sets the identifier name of this circuit breaker instance to orderGateway.
# this maps directly to your custom Resilience4j configuration (e.g., timeout limits, failure rate thresholds) in application.yml.
spring.cloud.gateway.server.webflux.routes[2].filters[0].args.name=orderGateway
# defines the internal URI where requests are forwarded when the downstream service fails or the circuit trips open. 
# forward:/ routes the request to a local controller endpoint within the Gateway itself rather than making an external call.
spring.cloud.gateway.server.webflux.routes[2].filters[0].args.fallbackUri=forward:/fallback/order

# --- ROUTE 4 : service-chatbot via Eureka ---
spring.cloud.gateway.server.webflux.routes[3].id=route-service-chatbot
# lb:// tells Spring to look up 'service-chatbot' registered in Eureka.
spring.cloud.gateway.server.webflux.routes[3].uri=lb://service-chatbot
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/chatbot/**
# RATE LIMITER CONFIGURATION: the Rate Limiter controls the frequency of incoming requests to protect the endpoint/service from spam or overuse.
# activates the RequestRateLimiterGatewayFilterFactory, which controls the flow of incoming HTTP requests.
spring.cloud.gateway.server.webflux.routes[3].filters[0].name=RequestRateLimiter
# defines how many tokens (requests) are added to the bucket every second. 
# in steady state, clients can make a maximum average of 2 requests per second.
spring.cloud.gateway.server.webflux.routes[3].filters[0].args.redis-rate-limiter.replenishRate=2
# defines the maximum token capacity of the bucket. 
# this allows clients to make a sudden burst of up to 5 requests in a single second before being rate-limited (HTTP 429 Too Many Requests).
spring.cloud.gateway.server.webflux.routes[3].filters[0].args.redis-rate-limiter.burstCapacity=5
# references a Spring Bean named userKeyResolver in your application context (using Spring Expression Language #{@...}). 
# this bean extracts the identification key (e.g., User ID, IP address, API key) from the request to track rate-limiting per client rather than globally.
spring.cloud.gateway.server.webflux.routes[3].filters[0].args.key-resolver=#{@userKeyResolver}

spring.main.web-application-type=reactive

# keep registration enabled so it connects when Eureka comes online.
# eureka.client.enabled=false
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true

# tells the client to wait longer between initial connection attempts (Default is 30).
eureka.client.initial-instance-info-replication-interval-seconds=60

# tells the client how often to retry fetching the registry if it fails (Default is 30).
eureka.client.registry-fetch-interval-seconds=60

# SILENCE THE LOG SPAM : hide the massive stack traces while it waits for Eureka.
logging.level.com.netflix.discovery=ERROR
logging.level.org.springframework.cloud.netflix.eureka=ERROR

# a secure base64 encoded HMAC-SHA256 key (keep this secret)
# jwt.secret=6x+B8K2N9qZ3wXvY5rT7mP1sQ9uV4xZ8A2bC5dE6fG7hI8jK9lM0nO1pQ2rS3tU4
# spring.security.oauth2.resourceserver.jwt.secret-key=6x+B8K2N9qZ3wXvY5rT7mP1sQ9uV4xZ8A2bC5dE6fG7hI8jK9lM0nO1pQ2rS3tU4
jwt.public-key-location=file:c:/project/superstore/keys/public.pem

# management.server.port=8079
# include prometheus in exposed endpoints
management.endpoints.web.exposure.include=health,prometheus
# optional : enable common metric tags (like application name)
management.metrics.tags.application=superstore
management.metrics.tags.service=${spring.application.name}
