spring.application.name=service-chatbot

server.port=8083

spring.datasource.url=jdbc:postgresql://localhost:5432/superstore
spring.datasource.username=superstore
spring.datasource.password=superstore
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.fetch_size=100

spring.cache.type=redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Spring AI Ollama Configuration
# What does temperature = 0.3 do?
# .temperature controls the randomness and creativity of the AI model's responses.
# low values  (0.0 – 0.3)  : make the output focused, deterministic, and factual.
# high values (0.7 – 1.0+) : Make the output more creative, diverse, and unpredictable.
# by setting it to 0.3, we are configuring our local LLM to give consistent, conservative, and precise answers - ideal for factual Q&A.  
spring.ai.ollama.base-url=http://localhost:11434
# spring.ai.ollama.chat.model=llama3.2
spring.ai.ollama.chat.model=llama3.2:1b
spring.ai.ollama.chat.temperature=0.3
spring.ai.ollama.embedding.model=nomic-embed-text
# limit context size (default 4096 or 8192)
spring.ai.ollama.chat.num-ctx=2048
# limits models maximum response length
spring.ai.ollama.chat.num-predict=256
# keeps ollama loaded indefinitely
spring.ai.ollama.chat.keep-alive=-1s
# set physical CPU core count (not logical hyperthreads)
spring.ai.ollama.chat.num-thread=4

# Spring AI PGVector Configuration
spring.ai.vectorstore.pgvector.index-type=HNSW
spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE
spring.ai.vectorstore.pgvector.dimensions=768
spring.ai.vectorstore.pgvector.initialize-schema=false
spring.ai.vectorstore.pgvector.schema-name=superstore
spring.ai.vectorstore.pgvector.table-name=vector_store
spring.ai.vectorstore.pgvector.id-type=text

# a secure base64 encoded HMAC-SHA256 key (keep this secret)
# jwt.secret=6x+B8K2N9qZ3wXvY5rT7mP1sQ9uV4xZ8A2bC5dE6fG7hI8jK9lM0nO1pQ2rS3tU4
# spring.security.oauth2.resourceserver.jwt.public-key-location=file:c:/project/superstore/keys/public.pem

# tells this service where the Eureka registry lives.
eureka.client.service-url.defaultZone=http://eureka:eureka@localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# keep registration enabled so it connects when Eureka comes online.
# eureka.client.enabled=false
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true

# tells the client to wait longer between initial connection attempts (Default is 30).
eureka.client.initial-instance-info-replication-interval-seconds=60

# tells the client how often to retry fetching the registry if it fails (Default is 30).
eureka.client.registry-fetch-interval-seconds=60

# SILENCE THE LOG SPAM : hide the massive stack traces while it waits for Eureka.
logging.level.com.netflix.discovery=ERROR
logging.level.org.springframework.cloud.netflix.eureka=ERROR

# Spring AI MCP client
spring.ai.mcp.client.name=service-chatbot
spring.ai.mcp.client.version=1.0.0
# spring.ai.mcp.client.type=ASYNC
# service-product-mcp-server exposed endpoint
# spring.ai.mcp.client.streamable-http.connections.server1.url=http://localhost:8081
# spring.ai.mcp.client.streamable-http.connections.server1.endpoint=/mcp
# spring.ai.mcp.client.streamable-http.connections.server2.url=http://otherserver:8082/mcp
